# Programming Assignment 2: Numerical Python (NumPy)

## Tolentino, Shiloh R.

## 2ECE-A

In [1]:
import numpy as np

### A. REPRODUCIBLE NORMALIZATION PROBLEM

In [2]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))

mean = X.mean()
std = X.std()

X_normalized = (X - mean)/std

In [3]:
print("Array of X: \n", X)
print("\n Normalized Array: \n", X_normalized)
print("\n Mean: \n", mean)
print("\nStandard Deviation: \n", std)

print("\n Normalized Mean: \n", X_normalized.mean())
print("\n Normalized Standard Deviation: \n", round(X_normalized.std(),1))

Array of X: 
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

 Normalized Array: 
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

 Mean: 
 46.36

Standard Deviation: 
 25.864075471588002

 Normalized Mean: 
 0.0

 Normalized Standard Deviation: 
 1.0


In [4]:
np.save("X_normalized.npy", X_normalized)

### B. CUBES DIVISBLE BY 4 PROBLEM

In [5]:
C = (np.arange(1, 101) **3).reshape(10, 10)

div_by_4 = C[C % 4 ==0]

print("Shape of C:\n", C.shape)
print("\n Arrays divisible by 4: \n", div_by_4) 
print("\n Number of Selected Elements:\n", div_by_4.size)

Shape of C:
 (10, 10)

 Arrays divisible by 4: 
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

 Number of Selected Elements:
 50


In [6]:
np.save("div_by_4.npy", div_by_4)

### C. ABOVE-MEAN SQUARES PROBLEM

In [7]:
S = (np.arange(1,37,1) **2).reshape(6,6)
S_mean = S.mean()
above_mean = S[S>S_mean]

print("Array S:")
print(S)
print("\nMean of S (S_mean):", S_mean)
print("\nElements above mean (above_mean):")
print(above_mean)
print("\nNumber of selected elements:", above_mean.size)

Array S:
[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

Mean of S (S_mean): 450.1666666666667

Elements above mean (above_mean):
[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

Number of selected elements: 15


In [8]:
np.save("above_mean.npy", above_mean)